// ------------------------------------------------------------------
// Component: //activeprompts notice formatter (#264)
// Responsibility: Pure render for the four-layer system-prompt
//                 composition each persona will receive at next
//                 dispatch — global, conversation (annotated for
//                 shadowing), per-persona override (with explicit-
//                 empty sentinel), and per-persona step note when
//                 a flow step has an instruction. Mirrors the join
//                 in builder.ts:113 so the user sees exactly what
//                 the LLM gets.
// Collaborators: lib/commands/handlers/info.ts (caller), lib/types.
// ------------------------------------------------------------------

import type { Persona } from "../types";

export interface ActivePromptsInput {
  globalPrompt: string | null;
  conversationPrompt: string | null;
  personas: readonly Persona[];
  // Per-persona step instruction to layer in. Keyed by persona.id.
  // Only populated when a flow is attached and the current/next
  // personas-step has an instruction; missing key = no step note.
  stepNotes?: Readonly<Record<string, string>>;
}

// Render a possibly-multi-line prompt as an indented markdown block.
// Plain-text indentation rather than fences so a long prompt with
// triple-backticks inside doesn't break the surrounding markdown.
function indented(text: string): string {
  return text
    .split("\n")
    .map((line) => `    ${line}`)
    .join("\n");
}

function localPromptSummary(
  persona: Persona,
  conversationPrompt: string | null,
): { source: string; rendered: string } {
  const override = persona.systemPromptOverride;
  if (override === null) {
    if (conversationPrompt === null || conversationPrompt === "") {
      return { source: "(none — no conversation prompt either)", rendered: "—" };
    }
    return { source: "from conversation", rendered: indented(conversationPrompt) };
  }
  if (override === "") {
    // ?? in builder.ts:93 stops here, then the `!!s` filter in :114
    // drops the empty string from the system block join. Net effect:
    // no local layer at all for this persona.
    return {
      source: "explicit empty — local layer skipped",
      rendered: "(empty — no local layer reaches the LLM)",
    };
  }
  return { source: "from persona override", rendered: indented(override) };
}

function shadowingAnnotation(personas: readonly Persona[]): string | null {
  if (personas.length === 0) return null;
  const overriding = personas.filter((p) => p.systemPromptOverride !== null).length;
  if (overriding === 0) return null;
  if (overriding === personas.length) {
    return "_Shadowed by all personas — never reaches the LLM for this conversation._";
  }
  return `_Shadowed by ${overriding} of ${personas.length} personas — only the remaining ${personas.length - overriding} see it._`;
}

export function formatActivePrompts(input: ActivePromptsInput): string {
  const { globalPrompt, conversationPrompt, personas, stepNotes } = input;
  const lines: string[] = ["## Active prompts"];

  // Top: shared inputs (global + conversation). Repeating these per
  // persona would be noise, since they don't vary across personas.
  lines.push("");
  lines.push("### Global (Settings → general.systemPrompt)");
  lines.push(globalPrompt && globalPrompt.trim() ? indented(globalPrompt) : "    _(empty)_");

  lines.push("");
  lines.push("### Conversation system prompt");
  lines.push(
    conversationPrompt && conversationPrompt !== ""
      ? indented(conversationPrompt)
      : "    _(empty)_",
  );
  const shadow = shadowingAnnotation(personas);
  if (shadow !== null) {
    lines.push("");
    lines.push(shadow);
  }

  if (personas.length === 0) {
    lines.push("");
    lines.push("_(no personas in this conversation — only the global prompt reaches the LLM)_");
    return lines.join("\n");
  }

  lines.push("");
  lines.push("### Per-persona effective system block");
  for (const p of personas) {
    lines.push("");
    lines.push(`#### ${p.name}`);
    // Identity is auto-generated by buildContext for any named persona,
    // so showing the canonical line — not the persona's localPrompt —
    // matches what the LLM actually sees.
    lines.push(
      `- **Identity:** \`You are ${p.name}. Only respond as yourself — do not include or generate responses for other personas.\``,
    );
    const local = localPromptSummary(p, conversationPrompt);
    lines.push(`- **Local prompt:** _${local.source}_`);
    lines.push(local.rendered);
    const step = stepNotes?.[p.id];
    if (step !== undefined && step.trim() !== "") {
      lines.push(`- **Step note:** _from current flow step_`);
      lines.push(indented(`Step note: ${step.trim()}`));
    }
  }

  return lines.join("\n");
}
