// ------------------------------------------------------------------
// Component: Persona types
// Responsibility: Persona record + resolver output types
// Collaborators: personas/service.ts, personas/resolver.ts,
//                orchestration/sendPlanner.ts, context/builder.ts
// ------------------------------------------------------------------

import type { ProviderId } from "./providers";

// Opaque stable id: "p_" + 8 random base36 chars. Generated by the
// persona service so renames don't break DAG edges or pin targets.
export type PersonaId = string;

export interface Persona {
  id: PersonaId;
  conversationId: string;
  provider: ProviderId;
  name: string;
  // Lowercased, punctuation-stripped form used for @-prefix matching.
  // Uniqueness is enforced per-conversation over active (non-tombstoned)
  // personas.
  nameSlug: string;
  systemPromptOverride: string | null;
  modelOverride: string | null;
  colorOverride: string | null;
  // Message index at which this persona was created. Messages before
  // this index are hidden from the persona's context (step 4 of the
  // context builder rules).
  createdAtMessageIndex: number;
  sortOrder: number;
  // DAG edge: parent persona id, or null for a root.
  // Tree/forest only (single parent). Multi-parent support is a future
  // ALTER TABLE if ever needed.
  runsAfter: PersonaId | null;
  // Tombstone (ms epoch). Null = active.
  deletedAt: number | null;
  // Provider-specific config. Currently only Apertus uses this — its
  // base URL embeds a per-persona Product-Id (#15). A second provider
  // with knobs would justify refactoring this to a JSON blob.
  apertusProductId: string | null;
}

// How the user's send intent was resolved.
// - "targeted": explicit @name(s) — ignores DAG.
// - "all": @all — DAG-active.
// - "others": @others — ignores DAG.
// - "implicit": no prefix, use current selection — DAG-active iff
//   selection spans multiple personas.
export type ResolveMode = "targeted" | "all" | "others" | "implicit";

// One resolved send destination. `personaId` is null for bare-provider
// sends (e.g. "@claude" with no persona of that name in the convo).
export interface PersonaTarget {
  provider: ProviderId;
  personaId: PersonaId | null;
  // Effective persona key = personaId ?? provider. Used throughout the
  // context builder and visibility matrix.
  key: string;
  // Display name for UI and error messages.
  displayName: string;
}
