// ------------------------------------------------------------------
// Component: Persona types
// Responsibility: Persona record + resolver output types
// Collaborators: personas/service.ts, personas/resolver.ts,
//                orchestration/sendPlanner.ts, context/builder.ts
// ------------------------------------------------------------------

import type { ProviderId } from "./providers";

// Opaque stable id: "p_" + 8 random base36 chars. Generated by the
// persona service so renames don't break DAG edges or pin targets.
export type PersonaId = string;

export interface Persona {
  id: PersonaId;
  conversationId: string;
  provider: ProviderId;
  name: string;
  // Lowercased, punctuation-stripped form used for @-prefix matching.
  // Uniqueness is enforced per-conversation over active (non-tombstoned)
  // personas.
  nameSlug: string;
  systemPromptOverride: string | null;
  modelOverride: string | null;
  colorOverride: string | null;
  // Message index at which this persona was created. Messages before
  // this index are hidden from the persona's context (step 4 of the
  // context builder rules).
  createdAtMessageIndex: number;
  sortOrder: number;
  // Tombstone (ms epoch). Null = active.
  deletedAt: number | null;
  // Provider-specific config. Currently only Apertus uses this — its
  // base URL embeds a per-persona Product-Id (#15). A second provider
  // with knobs would justify refactoring this to a JSON blob.
  apertusProductId: string | null;
  // #94: per-persona visibility defaults, keyed by persona nameSlug.
  // 'y' = this persona sees the other's output; 'n' = hidden.
  // Absent = use conversation default. Cross-editing keeps all
  // personas in the same conversation consistent.
  visibilityDefaults: Record<string, "y" | "n">;
  // #140 → #171: when provider === "openai_compat", points at the
  // configured preset whose URL template + headers + key the
  // adapter resolves at call time. Null for every other provider.
  openaiCompatPreset:
    | { kind: "builtin"; id: string }
    | { kind: "custom"; name: string }
    | null;
  // #213: per-persona role lens. Maps a source-speaker key (a persona-id
  // or the literal "user") to the role this persona should see for
  // that speaker. Default empty map = today's behavior (target's own
  // messages → assistant, everything else → assistant with name prefix,
  // human user → user). Lets one persona treat another persona's (or
  // the user's) messages as user-role for review/coaching scenarios.
  roleLens: Record<string, "user" | "assistant">;
  // #260: when true, this persona was added with scope="inherit" and
  // therefore sees the conversation's pre-creation history regardless
  // of `addressedTo` (on user rows) and `audience` (on assistant rows).
  // The cutoff at `createdAtMessageIndex` is also relaxed for inherit-
  // ing personas. Visibility matrix and pin-target filters still apply.
  // Optional with default false on read so callers building synthetic
  // Persona objects don't have to set it.
  inheritedHistory?: boolean;
}

// How the user's send intent was resolved.
// - "targeted": explicit @name(s) — ignores DAG.
// - "all": @all — DAG-active.
// - "others": @others — ignores DAG.
// - "implicit": no prefix, use current selection — DAG-active iff
//   selection spans multiple personas.
// - "convo": @convo — flow-aware. Resolver returns empty targets;
//   the resolveTargetsWithFlow wrapper inflates to the flow's next
//   personas-step (#216). When no flow is attached the wrapper
//   leaves targets empty so sendMessage rejects the send.
export type ResolveMode = "targeted" | "all" | "others" | "implicit" | "convo";

// One resolved send destination. `personaId` is null for bare-provider
// sends (e.g. "@claude" with no persona of that name in the convo).
export interface PersonaTarget {
  provider: ProviderId;
  personaId: PersonaId | null;
  // Effective persona key = personaId ?? provider. Used throughout the
  // context builder and visibility matrix.
  key: string;
  // Display name for UI and error messages.
  displayName: string;
}
